/********************************************************************
* c/esrio_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error c/esrio_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableesrio_dict();
extern void G__cpp_setup_inheritanceesrio_dict();
extern void G__cpp_setup_typetableesrio_dict();
extern void G__cpp_setup_memvaresrio_dict();
extern void G__cpp_setup_globalesrio_dict();
extern void G__cpp_setup_memfuncesrio_dict();
extern void G__cpp_setup_funcesrio_dict();
extern void G__set_cpp_environmentesrio_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/pbuehler/physics/projects/GO/2014/SIDSRoot/OnlineAnalysis/VisualAnalysis/data/EsrSMSEvent.h"
#include "/home/pbuehler/physics/projects/GO/2014/SIDSRoot/OnlineAnalysis/VisualAnalysis/data/EsrDecayEvent.h"
#include "/home/pbuehler/physics/projects/GO/2014/SIDSRoot/OnlineAnalysis/VisualAnalysis/data/EsrBinDecayEvent.h"
#include "/home/pbuehler/physics/projects/GO/2014/SIDSRoot/OnlineAnalysis/VisualAnalysis/data/EsrInjData.h"
#include "/home/pbuehler/physics/projects/GO/2014/SIDSRoot/OnlineAnalysis/VisualAnalysis/data/../SubTask/EsrTree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__esrio_dictLN_TClass;
extern G__linked_taginfo G__esrio_dictLN_TBuffer;
extern G__linked_taginfo G__esrio_dictLN_TMemberInspector;
extern G__linked_taginfo G__esrio_dictLN_TObject;
extern G__linked_taginfo G__esrio_dictLN_TNamed;
extern G__linked_taginfo G__esrio_dictLN_TString;
extern G__linked_taginfo G__esrio_dictLN_string;
extern G__linked_taginfo G__esrio_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__esrio_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__esrio_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__esrio_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__esrio_dictLN_EsrSMSEvent;
extern G__linked_taginfo G__esrio_dictLN_EsrBinDecayEvent;
extern G__linked_taginfo G__esrio_dictLN_EsrDecayEvent;
extern G__linked_taginfo G__esrio_dictLN_EsrInjData;
extern G__linked_taginfo G__esrio_dictLN_vectorlEEsrDecayEventcOallocatorlEEsrDecayEventgRsPgR;
extern G__linked_taginfo G__esrio_dictLN_reverse_iteratorlEvectorlEEsrDecayEventcOallocatorlEEsrDecayEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__esrio_dictLN_vectorlEEsrBinDecayEventcOallocatorlEEsrBinDecayEventgRsPgR;
extern G__linked_taginfo G__esrio_dictLN_reverse_iteratorlEvectorlEEsrBinDecayEventcOallocatorlEEsrBinDecayEventgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__esrio_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__esrio_dictLN_TFile;
extern G__linked_taginfo G__esrio_dictLN_TTree;
extern G__linked_taginfo G__esrio_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__esrio_dictLN_EsrTree;
extern G__linked_taginfo G__esrio_dictLN_vectorlEEsrInjDatacOallocatorlEEsrInjDatagRsPgR;
extern G__linked_taginfo G__esrio_dictLN_reverse_iteratorlEvectorlEEsrInjDatacOallocatorlEEsrInjDatagRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
